# Generated by Django 6.1.1 on 2026-09-10 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="guild",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="players",
                to="db.guild",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="race",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="db.race",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="race",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="db.race",
            ),
        ),
    ]
